workflow:
  rules:
    - if: $CI_COMMIT_TAG
    - if: $CI_MERGE_REQUEST_IID
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH

stages:
  - build

include:
  - local: .gitlab/common.yml
  # - template: Jobs/SAST.gitlab-ci.yml
  # - template: Jobs/Container-Scanning.gitlab-ci.yml
  # - template: Jobs/Secret-Detection.gitlab-ci.yml

base:
  extends: .build_job
  stage: .pre
  rules:
    - changes: [base/**/*]
  variables:
    CI_APPLICATION_REPOSITORY: $CI_REGISTRY_IMAGE
    IMAGE_PLATFORM: "linux/amd64,linux/arm64"
    IMAGE_SUFFIX: "/base"
  before_script:
    - cd base

build:
  extends: .build_job
  variables:
    IMAGE_PLATFORM: "linux/amd64,linux/arm64"
