variables:
  TEST_DISABLED: "true"
  CODE_QUALITY_DISABLED: "true"

include:
  - template: Auto-DevOps.gitlab-ci.yml
  - .gitlab/common.yml

build:
  extends: .build_job
  image: registry.gitlab.com/ericvh/docker-buildx-qemu
  before_script:
    - update-binfmts --enable # Important: Ensures execution of other binary formats is enabled in the kernel
    # - docker buildx create --driver docker-container --use
    # - docker buildx inspect --bootstrap
    # - docker buildx ls
