workflow:
  rules:
    - if: $CI_COMMIT_TAG
    - if: $CI_MERGE_REQUEST_IID
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH

stages:
  - build

include:
  - local: .gitlab/common.yml
  # - template: Jobs/SAST.gitlab-ci.yml
  # - template: Jobs/Container-Scanning.gitlab-ci.yml
  # - template: Jobs/Secret-Detection.gitlab-ci.yml

build:
  extends: .build_job
  variables:
    IMAGE_PLATFORM: "linux/amd64,linux/arm64"
